name: Chrome

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      BROWSERS: selenium:chrome

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Test
        run: |
          cd packages/tests
          npm run test

      - name: Test SSR
        run: |
          cd packages/labs/ssr
          npm run test:integration
