name: IE11

on: [push, pull_request]

jobs:
  tests-ie11:
    # Don't run on forks. Sauce tests need access to secrets.
    if: github.repository == 'lit/lit'

    # Sauce tests are still unreliable. Run them, but don't mark a commit as
    # failing if it fails.
    continue-on-error: true

    runs-on: windows-latest
    env:
      BROWSERS: selenium:ie

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Test
        run: |
          cd packages/tests
          npm run test

      - name: Test SSR
        run: |
          cd packages/labs/ssr
          npm run test:integration
