name: Safari

on: [push, pull_request]

jobs:
  tests:
    # Don't run on forks. Sauce tests need access to secrets.
    if: github.repository == 'lit/lit'

    runs-on: macos-latest
    env:
      BROWSERS: selenium:safari
      CONCURRENT_FRAMES: 1

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Test
        run: |
          cd packages/tests
          npm run test

      - name: Test SSR
        run: |
          cd packages/labs/ssr
          npm run test:integration
