name: Tests

on: [push, pull_request]

jobs:
  presubmit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - uses: google/wireit@setup-github-actions-caching/v1

      # only checkout main when merging to main?
      # if merge main, checkout main
      - run: git checkout main
      - run: git checkout ${{ github.sha }}

      - name: Install NPM Dependencies
        run: npm ci

      # Enforce that all PRs that change packages need changesets. Changes
      # without changesets result in this job failing.
      - name: Changeset
        # When lit-robot creates a release PR, skip this check as it will always
        # fail.
        if: ${{ github.actor != 'lit-robot' }}
        run: npm run changeset status -- --since=main

      - name: Lint
        run: npm run lint

      - name: Install playwright deps
        run: npx playwright install-deps

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Test
        env:
          BROWSERS: preset:local
        run: npm run test
      
  windows-tools:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build --  --scope @lit-labs/analyzer --scope @lit-labs/gen-utils --scope @lit-labs/gen-wrapper-react --scope @lit-labs/cli

      - name: Test
        run: npm run test -- --scope @lit-labs/analyzer --scope @lit-labs/gen-utils --scope @lit-labs/gen-wrapper-react --scope @lit-labs/cli


